<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="publicationMIM2025Metamodels" nsURI="http://www.example.org/publicationMIM2025Metamodels"
    nsPrefix="publicationMIM2025Metamodels">
  <eClassifiers xsi:type="ecore:EClass" name="ModellingEntity" eSuperTypes="#//PlatformFramework_NamedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
        eType="#//Container" eOpposite="#//Container/contains"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//ModellingEntity" eOpposite="#//ModellingEntity/container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperContainer" eType="#//Container"
        eOpposite="#//Container/subContainers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subContainers" upperBound="-1"
        eType="#//Container" eOpposite="#//Container/upperContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RECP" eSuperTypes="#//Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patternsCatalogs" lowerBound="1"
        upperBound="-1" eType="#//PatternsCatalog" eOpposite="#//PatternsCatalog/recp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RECPObjective" eType="#//RECPObjective"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternsCatalog">
    <eStructuralFeatures xsi:type="ecore:EReference" name="recp" eType="#//RECP" eOpposite="#//RECP/patternsCatalogs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patterns" eType="#//Pattern"
        eOpposite="#//Pattern/patternsCatalog"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern" eSuperTypes="#//ModellingEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patternsCatalog" lowerBound="1"
        upperBound="-1" eType="#//PatternsCatalog" eOpposite="#//PatternsCatalog/patterns"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="problem" lowerBound="1"
        eType="#//Problem" eOpposite="#//Problem/problemSolvedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="solutions" lowerBound="1"
        upperBound="-1" eType="#//Solution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedPatternRelationships"
        upperBound="-1" eType="#//PatternRelationShip"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryRole" eType="#//PatternRoleType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondaryRole" eType="#//PatternSecondaryRoleType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Solution" eSuperTypes="#//ModellingEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelledBy" upperBound="-1"
        eType="#//DigitalEntityModel" eOpposite="#//DigitalEntityModel/modelsSolutions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Problem" eSuperTypes="#//ModellingEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="problemSolvedBy" upperBound="-1"
        eType="#//Pattern" eOpposite="#//Pattern/problem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="solutions" upperBound="-1"
        eType="#//Adequation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelledBy" upperBound="-1"
        eType="#//DigitalEntityModel" eOpposite="#//DigitalEntityModel/modelsProblems"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Adequation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="problems" upperBound="-1"
        eType="#//Problem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="solutions" upperBound="-1"
        eType="#//Solution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isValidInContexts" upperBound="-1"
        eType="#//Context" eOpposite="#//Context/validsContextOf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context" eSuperTypes="#//ModellingEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="validsContextOf" upperBound="-1"
        eType="#//Adequation" eOpposite="#//Adequation/isValidInContexts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlatformFramework_NamedObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigitalEntityModel" eSuperTypes="#//ModellingEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelsSolutions" upperBound="-1"
        eType="#//Solution" eOpposite="#//Solution/modelledBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelsProblems" upperBound="-1"
        eType="#//Problem" eOpposite="#//Problem/modelledBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigitalTwinEntity" eSuperTypes="#//DigitalEntityModel #//ModellingEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digitalTwinSystem" lowerBound="1"
        eType="#//DigitalTwinSystem" eOpposite="#//DigitalTwinSystem/digitalTwinEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigitalTwinSystem" eSuperTypes="#//ModellingEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digitalTwinEntity" lowerBound="1"
        eType="#//DigitalTwinEntity" eOpposite="#//DigitalTwinEntity/digitalTwinSystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usage" lowerBound="1" eType="#//Usage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternRelationShip">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePattern" lowerBound="1"
        upperBound="-1" eType="#//Pattern" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPattern" lowerBound="1"
        upperBound="-1" eType="#//Pattern" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RECPObjective">
    <eLiterals name="RECP_Method"/>
    <eLiterals name="RECP_Project" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Usage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="capabilities" upperBound="-1"
        eType="#//Capability" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalRequirement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tobeMetThrough" lowerBound="1"
        eType="#//Capability" eOpposite="#//Capability/functionalRequirementsToMeet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Capability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionalRequirementsToMeet"
        lowerBound="1" upperBound="-1" eType="#//FunctionalRequirement" eOpposite="#//FunctionalRequirement/tobeMetThrough"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PatternRoleType">
    <eLiterals name="NotYetDefined"/>
    <eLiterals name="Modelling" value="1"/>
    <eLiterals name="Evaluation" value="2"/>
    <eLiterals name="Organisational" value="3"/>
    <eLiterals name="Technical" value="4"/>
    <eLiterals name="Validation" value="5"/>
    <eLiterals name="..." value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PatternSecondaryRoleType">
    <eLiterals name="NotYetDefined"/>
    <eLiterals name="FunctionalArchitecture" value="1"/>
    <eLiterals name="Requirement" value="2"/>
    <eLiterals name="Usage" value="5"/>
    <eLiterals name="LogicalArchitecture" value="10"/>
    <eLiterals name="PhysicalArchitecture" value="11"/>
    <eLiterals name="Design" value="15"/>
    <eLiterals name="..." value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass18"/>
</ecore:EPackage>
